# Generated by Django 4.0.6 on 2025-06-22 06:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hours_tracker', '0003_customuser_account_number_customuser_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='workhours',
            options={'ordering': ['-date', 'user'], 'verbose_name': 'Work Hours', 'verbose_name_plural': 'Work Hours'},
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workhours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this record was first created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workhours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last modified'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='minimum_wage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Minimum wage cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0, message='Hours cannot be negative.'), django.core.validators.MaxValueValidator(24.0, message='Hours cannot exceed 24 per day.')]),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='holiday_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workhours',
            index=models.Index(fields=['date'], name='workhours_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workhours',
            index=models.Index(fields=['user', 'date'], name='workhours_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='workhours',
            index=models.Index(fields=['created_at'], name='workhours_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workhours',
            index=models.Index(fields=['is_absence'], name='workhours_absence_idx'),
        ),
    ]
